[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
contracts_solana = "26zEAde3YAxwhy8mkyshsx7FhyfNJKHzU7cVLkdt895u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
